/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicV1AnomaliesRouteImport } from './routes/api/public/v1/anomalies'
import { Route as ApiPublicV1RoutesRouteImport } from './routes/api/public/v1/routes'
import { Route as ApiPublicV1SeriesRouteImport } from './routes/api/public/v1/series'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AnomaliesRoute = ApiPublicV1AnomaliesRouteImport.update({
  id: '/api/public/v1/anomalies',
  path: '/api/public/v1/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1RoutesRoute = ApiPublicV1RoutesRouteImport.update({
  id: '/api/public/v1/routes',
  path: '/api/public/v1/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SeriesRoute = ApiPublicV1SeriesRouteImport.update({
  id: '/api/public/v1/series',
  path: '/api/public/v1/series',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/v1/anomalies': typeof ApiPublicV1AnomaliesRoute
  '/api/public/v1/routes': typeof ApiPublicV1RoutesRoute
  '/api/public/v1/series': typeof ApiPublicV1SeriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/v1/anomalies': typeof ApiPublicV1AnomaliesRoute
  '/api/public/v1/routes': typeof ApiPublicV1RoutesRoute
  '/api/public/v1/series': typeof ApiPublicV1SeriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/v1/anomalies': typeof ApiPublicV1AnomaliesRoute
  '/api/public/v1/routes': typeof ApiPublicV1RoutesRoute
  '/api/public/v1/series': typeof ApiPublicV1SeriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/v1/anomalies'
    | '/api/public/v1/routes'
    | '/api/public/v1/series'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/v1/anomalies'
    | '/api/public/v1/routes'
    | '/api/public/v1/series'
  id:
    | '__root__'
    | '/'
    | '/api/public/v1/anomalies'
    | '/api/public/v1/routes'
    | '/api/public/v1/series'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicV1AnomaliesRoute: typeof ApiPublicV1AnomaliesRoute
  ApiPublicV1RoutesRoute: typeof ApiPublicV1RoutesRoute
  ApiPublicV1SeriesRoute: typeof ApiPublicV1SeriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/anomalies': {
      id: '/api/public/v1/anomalies'
      path: '/api/public/v1/anomalies'
      fullPath: '/api/public/v1/anomalies'
      preLoaderRoute: typeof ApiPublicV1AnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/routes': {
      id: '/api/public/v1/routes'
      path: '/api/public/v1/routes'
      fullPath: '/api/public/v1/routes'
      preLoaderRoute: typeof ApiPublicV1RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/series': {
      id: '/api/public/v1/series'
      path: '/api/public/v1/series'
      fullPath: '/api/public/v1/series'
      preLoaderRoute: typeof ApiPublicV1SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicV1AnomaliesRoute: ApiPublicV1AnomaliesRoute,
  ApiPublicV1RoutesRoute: ApiPublicV1RoutesRoute,
  ApiPublicV1SeriesRoute: ApiPublicV1SeriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
